export const listOfContents = [
  {
    id: 1,
    title: 'Como é o diagnóstico',
    items: [
      'Encontrando deficiências hormonais.',
      'O que deve ser incluído em uma consulta para terapia hormonal?',
      'Investigação curta ou abrangente?',
      'O que investigar inicialmente?',
      'Quais são os exames laboratoriais necessários?',
      'Quando começa uma deficiência hormonal?',
      'O que é uma deficiência evidente?',
      'O que são deficiências limítrofes?',
      'O que é um nível hormonal ótimo?',
    ],
  },
  {
    id: 4,
    title: 'Acompanhamento dos tratamentos Hormonais',
    items: [
      'O que investigar durante o acompanhamento?',
      'Quando solicitar os exames laboratoriais durante o acompanhamento?',
      'Quais exames laboratoriais devem ser feitos?',
    ],
  },
  {
    id: 7,
    title: 'Efeitos psicológicos da ocitocina',
    items: [
      'Efeitos físicos da ocitocina',
      'Funções específicas da ocitocina nas mulheres',
      'Funções específicas da ocitocina nos homens',
      'Produção de ocitocina',
      'Fatores que afetam a produção e/ou níveis de ocitocina',
      'Como detectar a deficiência',
      'Sintomas físicos e mentais da deficiência de Ocitocina',
      'Sinais físicos e da deficiência de Ocitocina',
      'Susceptibilidade a doenças',
      'Exames laboratoriais ',
      'Susceptibilidade a doenças',
      'Deficiência de ocitocina: TRATAMENTO',
      'Qual a melhor via de administração para o tratamento com ocitocina?',
      'Indicações para tratamento com ocitocina',
      'Contraindicações ao tratamento com ocitocina nos homens',
      'Como iniciar o tratamento com ocitocina',
      'SOLUCIONADOR DE PROBLEMAS para a ocitocina.',
    ],
  },
  {
    id: 11,
    title: 'testosterona nas mulheres',
    items: [
      'Produção de testosterona',
      'Declínio progressivo dos níveis de testosterona com a idade',
      'Que fatores podem influenciar a produção de testosterona?',
      'Principais metabólitos da testosterona',
      'Como detectar a deficiência de testosterona em mulheres?',
      'Sintomas de deficiência de Testosterona',
      'Sinais físicos de deficiência de Testosterona',
      'Susceptibilidade a doenças',
      'Exames laboratoriais, sangue, saliva e urina',
      'Terapias corretivas',
      'Como evitar o crescimento excessivo de pelos corporais',
      'Indicações para tratamento com testosterona em mulheres',
      'Contraindicações ao tratamento com testosterona em mulheres',
      'Quando ajustar a dose',
      'Evite subdosar e sobredosar',
      'Problemas relacionados a sobredosagem',
      'Conversão em DHT',
      'Problemas de excesso e ineficiência ',
    ],
  },
  {
    id: 2,
    title: 'Resolvendo deficiências Hormonais',
    items: [
      'Tratamento de deficiências hormonais',
      'Os tratamentos hormonais inibem a atividade das glândulas endócrinas?',
      'Como Tratar',
      'Torne o tratamento mais eficiente',
    ],
  },
  {
    id: 5,
    title: 'Sobre a Melatonina',
    items: [
      'Funções da melatonina',
      'Produção de melatonina',
      'Fatores que aumentam a produção de melatonina durante a noite',
      'Como detectar a deficiência de melatonina?',
      'Sintomas da deficiência de melatonina',
      'Sinais físicos da deficiência de melatonina',
      'Susceptibilidade a doenças',
      'Exames laboratoriais para melatonina',
      'Deficiência de melatonina: TRATAMENTO',
      'Como iniciar a terapia de melatonina',
      'Indicações para o tratamento com melatonina',
      'Contraindicações ao tratamento com melatonina',
      'SOLUCIONADOR DE PROBLEMAS para a melatonina',
    ],
  },
  {
    id: 8,
    title: 'Tireoide: Informações importantes',
    items: [
      'Funções dos hormônios tireoidianos',
      'Produção de hormônios tireoidianos',
      'Fatores que aumentam a produção de hormônios da tireoide',
      'Principais metabólitos dos hormônios tireoidianos',
      'Hipotireoidismo: Diagnóstico',
      'Como determinar inicio',
      'Sintomas de hipotireoidismo',
      'Sinas do hipotireoidismo',
      'Susceptibilidade a doenças',
      'Exames laboratoriais ',
      'Quais exames de imagem detectam anomalias da tireoide?',
      'Susceptibilidade a doenças',
      'Hipotireoidismo: TRATAMENTO ',
      'Porque T3 e T4',
      'Como iniciar a terapia tireoidiana',
      'Pacientes com hipotireoidismo e deficiência de cortisol',
      'Indicações para tratamento ',
      'Contraindicações ao tratamento ',
      'Quando adaptar a dose',
      'Que exames laboratoriais ajudam a controlar o tratamento da tireoide?',
      'Quais são os resultados laboratoriais ótimos para acompanhamento?',
      'SOLUCIONADOR DE PROBLEMAS sobredosagem',
      'Tratamento ineficiente',
    ],
  },
  {
    id: 12,
    title: 'testosterona nos homens',
    items: [
      'Produção de testosterona',
      'Fatores que afetam a produção de testosterona',
      'Deficiência de testosterona em homens: DIAGNÓSTICO',
      'Sintomas de deficiência de Testosterona',
      'Sinais físicos de deficiência de Testosterona',
      'Susceptibilidade a doenças',
      'Exames de imagem',
      'Exames laboratoriais sangue, urina e saliva',
      'Vias de administração',
      'Indicações para tratamento com testosterona em homens',
      'Contraindicações ao tratamento com testosterona nos homens',
      'Como reduzir níveis de estrogênios',
      'Sinais típicos de excesso de testosterona',
      'Problemas comportamentais',
      'Conversão excessiva em DHT',
      'Tratamentos ineficientes',
      'Problemas genitais',
    ],
  },
  {
    id: 3,
    title: 'TRATAR AS deficiências hormonais',
    items: [
      'Os tratamentos hormonais inibem a atividade das glândulas endócrinas?',
      'Como Tratar',
      'Torne o tratamento mais eficiente',
    ],
  },
  {
    id: 6,
    title: 'Sobre Hormônio do Crescimento',
    items: [
      'Produção de hormônio do crescimento (GH)',
      'Níveis de hormônio do crescimento',
      'Como detectar a deficiência de GH?',
      'Sinais físicos da deficiência de GH',
      'Sintomas da deficiência de GH',
      'Susceptibilidade a doenças',
      'Exames laboratoriais para hormônio do crescimento',
      'Deficiência  TRATAMENTO',
      'Como iniciar o tratamento com GH?',
      'Secretagogos ',
      'Indicações para o tratamento com GH',
      'Contraindicações ao tratamento GH',
      'Evite sobredosar',
      'Solucionando problemas',
      'Problemas raros',
    ],
  },
  {
    id: 9,
    title: 'CORTISOL: Informações importantes',
    items: [
      'Produção de cortisol',
      'Fatores que aumentam a produção de cortisol',
      'Como detectar a deficiência de cortisol',
      'Como determinar o inicio',
      'Sintomas da deficiência de cortisol',
      'Sinais físicos',
      'Suscetibilidade a doenças',
      'Exames laboratoriais para o cortisol',
      'Medicamentos',
      'Qual o melhor medicamento glicocorticoide?',
      'Como iniciar',
      'Como prevenir os efeitos adversos do cortisol',
      'Indicações',
      'Contraindicações ao tratamento com glicocorticoides',
      'Progresso do tratamento',
      'Acompanhamento do tratamento',
      'Quando adaptar dose',
      'Exames laboratoriais',
      'Evite sobredosar ou subdosar',
      'SOLUCIONADOR DE PROBLEMAS sobredosagem',
      'Tratamento ineficiente, intolerâncias',
      'Como escolher qual medicação, dosagem',
    ],
  },
  {
    id: 13,
    title: 'PROGESTERONA: Informações básicas',
    items: [
      'Possíveis funções incluem:',
      'Produção de progesterona',
      'Deficiência de progesterona masculina: DIAGNÓSTICO',
      'Sintomas da deficiência da progesterona em homens',
      'Sinais físicos da deficiência de progesterona em homens',
      'Susceptibilidade a doenças',
      'Exames laboratoriais sangue, urina e saliva',
      'Vias de administração',
      'Indicações para tratamento com progesterona em homens',
      'Contraindicações para o tratamento com progesterona em homens',
      'Como iniciar o tratamento com progesterona',
      'Problemas da conversão da progesterona',
    ],
  },
  {
    id: 10,
    title: 'Estrógeno e Progesterona',
    items: [
      'Hormônios femininos: Informações básicas',
      'Funções dos estrógenos e da progesterona',
      'Efeitos complementares dos estrógenos e da progesterona',
      'Produção dos estrógenos e da progesterona',
      'Fatores que influenciam a produção de estrógenos e progesterona',
      'Hormônios femininos e o processo de envelhecimento',
      'Como detectar deficiências hormonais femininas?',
      'Como determinar inicio',
      'Sintomas de deficiência hormonal feminina',
      'Sinais físicos',
      'Susceptibilidade a doenças',
      'Exames de imagem para a detecção de patologias relacionadas à disfunção ovariana',
      'Exames laboratoriais, sangue, saliva e urina',
      'Terapias corretivas',
      'Indicações para o tratamento com estrógeno e progesterona',
      'Contraindicações ao tratamento com hormônios femininos',
      'Influencia de outros hormônios ',
      'Sobredosagem manejo',
      'Problemas com Estrogênio baixo e sobredosagem',
      'Problemas com Progesterona baixa e sobredosagem',
      'Efeitos paradoxais',
      'Problemas inesperados',
      'Exemplos de tratamentos',
      'Como iniciar, como tomar, como tratar, como diferenciar.',
    ],
  },
  {
    id: 14,
    title: 'Revisões Rápidas',
    items: [
      'Sintomas mentais das deficiência hormonais',
      'Sintomas físicos das deficiências hormonais',
      'Sinais físicos das deficiências hormonais',
      'Deficiência hormonal X hiperlipidemia X hipertensão arterial x insuficiência cardíaca x câncer de mama x obesidade x diabetes x osteoporose x depressão x ansiedade ',
      'Exames séricos',
      'Exames de urina 24h',
      'Exames de acompanhamento',
      'Terapias hormonais corretivas',
    ],
  },
];
